from __future__ import annotations

from pathlib import Path
from typing import Iterable

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
)

from utils import money, safe_str, now_india


def _header(canvas, doc, title: str, subtitle: str = "SELVA MOTORS | HERO TWO WHEELER DEALERSHIP") -> None:
    canvas.saveState()
    width, height = A4
    canvas.setFillColor(colors.HexColor("#e31837"))
    canvas.rect(0, height - 22 * mm, width, 22 * mm, stroke=0, fill=1)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 18)
    canvas.drawString(15 * mm, height - 12 * mm, "HERO")
    canvas.setFont("Helvetica-Bold", 11)
    canvas.drawRightString(width - 15 * mm, height - 11 * mm, subtitle)
    canvas.setFillColor(colors.HexColor("#111827"))
    canvas.setFont("Helvetica-Bold", 14)
    canvas.drawString(15 * mm, height - 30 * mm, title)
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#6b7280"))
    canvas.drawRightString(width - 15 * mm, height - 30 * mm, now_india().strftime("%d-%m-%Y %I:%M %p"))
    canvas.restoreState()


def _footer(canvas, doc) -> None:
    canvas.saveState()
    width, _ = A4
    canvas.setStrokeColor(colors.HexColor("#e5e7eb"))
    canvas.line(15 * mm, 12 * mm, width - 15 * mm, 12 * mm)
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#6b7280"))
    canvas.drawString(15 * mm, 7 * mm, "Generated by SELVA MOTORS ERP")
    canvas.drawRightString(width - 15 * mm, 7 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _styled_doc(output_path: str | Path, title: str):
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="HeroTitle", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=16, textColor=colors.HexColor("#111827"), spaceAfter=6))
    styles.add(ParagraphStyle(name="HeroBody", parent=styles["BodyText"], fontName="Helvetica", fontSize=9, leading=12))
    doc = SimpleDocTemplate(str(output_path), pagesize=A4, rightMargin=16*mm, leftMargin=16*mm, topMargin=40*mm, bottomMargin=18*mm)
    return doc, styles


def _build_table(data, col_widths=None, header_bg="#111827"):
    tbl = Table(data, colWidths=col_widths, repeatRows=1)
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(header_bg)),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#cbd5e1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.HexColor("#f8fafc")]),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return tbl


def invoice_pdf(output_path: str | Path, record: dict, items: list[dict] | None = None) -> Path:
    doc, styles = _styled_doc(output_path, "Invoice")
    story = []
    story.append(Paragraph("SELVA MOTORS", styles["HeroTitle"]))
    story.append(Paragraph("Professional Invoice", styles["Heading2"]))
    story.append(Spacer(1, 5))

    meta_rows = [
        ["Invoice No", safe_str(record.get("Invoice Number"))],
        ["Job Card No", safe_str(record.get("Job Card Number"))],
        ["Customer", safe_str(record.get("Customer Name", record.get("Customer")))],
        ["Mobile", safe_str(record.get("Mobile Number"))],
        ["Vehicle", safe_str(record.get("Registration Number"))],
        ["Bike Model", safe_str(record.get("Bike Model"))],
        ["Date", safe_str(record.get("Date"))],
    ]
    story.append(_build_table([["Field", "Value"]] + meta_rows, [40*mm, 130*mm]))

    story.append(Spacer(1, 10))
    rows = [["Particulars", "Amount"]]
    for key in ["Spare Amount", "Oil Amount", "Labour Amount", "Other Charges"]:
        if safe_str(record.get(key, "")) != "":
            rows.append([key, money(record.get(key, 0))])
    rows.append(["Grand Total", money(record.get("Grand Total", 0))])
    story.append(_build_table(rows, [130*mm, 40*mm], header_bg="#e31837"))

    if items:
        story.append(Spacer(1, 10))
        item_rows = [["Item", "Qty", "Rate", "Total"]]
        for it in items:
            item_rows.append([
                safe_str(it.get("Item")),
                safe_str(it.get("Qty", 1)),
                money(it.get("Rate", 0)),
                money(it.get("Total", 0)),
            ])
        story.append(_build_table(item_rows, [65*mm, 20*mm, 30*mm, 30*mm]))

    story.append(Spacer(1, 12))
    story.append(Paragraph("Thank you for choosing Hero.", styles["HeroBody"]))
    doc.build(story, onFirstPage=lambda c, d: (_header(c, d, "INVOICE"), _footer(c, d)), onLaterPages=lambda c, d: (_header(c, d, "INVOICE"), _footer(c, d)))
    return Path(output_path)


def job_card_pdf(output_path: str | Path, record: dict) -> Path:
    doc, styles = _styled_doc(output_path, "Job Card")
    story = [
        Paragraph("SELVA MOTORS", styles["HeroTitle"]),
        Paragraph("Job Card", styles["Heading2"]),
        Spacer(1, 8),
        _build_table(
            [["Field", "Value"]] + [[k, safe_str(v)] for k, v in record.items() if k in [
                "Job Card Number", "Date", "Customer Name", "Mobile Number", "Registration Number", "Bike Model",
                "Service Type", "Complaint", "Advisor Name", "Technician Name", "Status", "Estimate Amount"
            ]],
            [55*mm, 125*mm]
        )
    ]
    doc.build(story, onFirstPage=lambda c, d: (_header(c, d, "JOB CARD"), _footer(c, d)), onLaterPages=lambda c, d: (_header(c, d, "JOB CARD"), _footer(c, d)))
    return Path(output_path)


def attendance_pdf(output_path: str | Path, df, title: str = "Attendance Report") -> Path:
    doc, styles = _styled_doc(output_path, title)
    story = [Paragraph("SELVA MOTORS", styles["HeroTitle"]), Paragraph(title, styles["Heading2"]), Spacer(1, 8)]
    if df is None or len(df) == 0:
        story.append(Paragraph("No records found.", styles["HeroBody"]))
    else:
        table_data = [list(df.columns)] + df.astype(str).values.tolist()
        story.append(_build_table(table_data))
    doc.build(story, onFirstPage=lambda c, d: (_header(c, d, title.upper()), _footer(c, d)), onLaterPages=lambda c, d: (_header(c, d, title.upper()), _footer(c, d)))
    return Path(output_path)


def report_pdf(output_path: str | Path, title: str, summary_rows: list[list[str]], detail_df=None) -> Path:
    doc, styles = _styled_doc(output_path, title)
    story = [Paragraph("SELVA MOTORS", styles["HeroTitle"]), Paragraph(title, styles["Heading2"]), Spacer(1, 8)]
    story.append(_build_table([["Metric", "Value"]] + summary_rows, [65*mm, 110*mm], header_bg="#e31837"))
    if detail_df is not None and len(detail_df) > 0:
        story.append(Spacer(1, 10))
        story.append(_build_table([list(detail_df.columns)] + detail_df.astype(str).values.tolist()))
    doc.build(story, onFirstPage=lambda c, d: (_header(c, d, title.upper()), _footer(c, d)), onLaterPages=lambda c, d: (_header(c, d, title.upper()), _footer(c, d)))
    return Path(output_path)
